# syntax=docker/dockerfile:1
FROM golang:1.16
WORKDIR /go/src/github.com/dfiduk/testing
COPY main.go ./
RUN go get -d -v github.com/dfiduk/testing \
  && CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .
